function createfigureErrores289(yvector1)
%CREATEFIGURE(yvector1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 26-Jan-2022 01:10:29

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar1 = bar(yvector1);

% The following line demonstrates an alternative way to create a data tip.
% datatip(bar1,6,2.20749649186631e-16);
% Create datatip
datatip(bar1,'DataIndex',6);

% Create ylabel
ylabel({'Error'});

% Create title
title({'Errores matriz 289x289'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2.86407772549634 10.2454736745037]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-3.02777736876713e-11 3.15853202631233e-09]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(gca,'xtick',1:6);
set(gca,'xticklabel', {'LU' 'Cholesky' 'QR' 'Jacobi' 'Jacobi-Seidel' 'SOR'});
