function createfigureMedias(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Dec-2021 19:38:44

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Método Crout','Color',[0 1 0]);
set(plot1(2),'DisplayName','Método Jacobi','LineStyle','--',...
    'Color',[1 0.411764705882353 0.16078431372549]);
set(plot1(3),'DisplayName','Método Gram-Schmidt','LineStyle',':',...
    'Color',[0.149019607843137 0.149019607843137 0.149019607843137]);

% Create ylabel
ylabel({'Valor'});

% Create xlabel
xlabel({'Iteración'});

% Create title
title({'Valores medios de las soluciones entre métodos'});

hold(axes1,'off');
% Create legend
legend(axes1,'show');

