function createfigureErrores(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Dec-2021 19:36:55

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',1.5,'Parent',axes1);
set(plot1(1),'DisplayName','Método Crout');
set(plot1(2),'DisplayName','Método Jacobi');
set(plot1(3),'DisplayName','Método Gram-Schmidt');

% Create ylabel
ylabel({'Error'},'HorizontalAlignment','center');

% Create xlabel
xlabel({'Iteración'},'HorizontalAlignment','center');

% Create title
title({'Errores para cada uno de los métodos'},...
    'HorizontalAlignment','center',...
    'FontWeight','bold');

hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[0 0 0]);

