function createfigureIntegrales(ymatrix1)
%CREATEFIGURE(ymatrix1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 17-Jan-2022 02:45:01

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(4),'DisplayName','Pchip');
set(bar1(3),'DisplayName','Lineal');
set(bar1(2),'DisplayName','Spline');
set(bar1(1),'DisplayName','Valores originales');

% The following line demonstrates an alternative way to create a data tip.
% datatip(bar1(4),6.72727272727273,768320);
% Create datatip
datatip(bar1(4),'DataIndex',7);

% Create ylabel
ylabel('Valor de la integral','HorizontalAlignment','center');

% Create xlabel
xlabel({'Regiones',''},'HorizontalAlignment','center');

% Create title
title('Comparación de integrales','HorizontalAlignment','center',...
    'FontWeight','bold');

hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.0251736345875858 0.85764914485211 0.0765624985098839 0.0714285694682953]);

