function createfigureErrorMSE(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Jan-2022 04:11:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

% Create title
title({'Error MSE'});

box(axes1,'on');
hold(axes1,'off');
