function createfigureComparacionCurvasP3(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Jan-2022 03:51:02

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1);
set(plot1(1),'DisplayName','Curva ajustada');
set(plot1(2),'DisplayName','Aproximacion grado 3');

% Create title
title({'Comparación curva ajustada vs Aproximación polinomio grado 3'});

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

