function createfigureDiarioAjustado(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Jan-2022 02:17:55

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1);
set(plot1(1),'DisplayName','Vector diario');
set(plot1(2),'DisplayName','Curva ajustada');

% Create ylabel
ylabel({'Contagios'});

% Create xlabel
xlabel({'Días'});

% Create title
title({'Vector diario Valparaiso vs Curva ajustada'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 700]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1000]);
box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.142361112383919 0.877526551168559 0.0687499987427146 0.0375128458852269]);

