function createfigureDistribucion(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Jan-2022 02:48:54

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','matrizDistribucion(:,1)');
set(plot1(2),'DisplayName','matrizDistribucion(:,2)');
set(plot1(3),'DisplayName','matrizDistribucion(:,3)');
set(plot1(4),'DisplayName','matrizDistribucion(:,4)');

% Create title
title({'Generación coeficientes iniciales polinomio grado 3'});

box(axes1,'on');
hold(axes1,'off');
