function createfigureTiempos(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Jan-2022 04:15:30

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

% Create title
title({'Comparación tiempos'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1.00921658986175 3.00921658986175]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[399.532573765703 479.532573765703]);
box(axes1,'on');
hold(axes1,'off');
