function createfigureGeneradores(ymatrix1)
%CREATEFIGURE(ymatrix1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 25-Jan-2022 02:32:29

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1);
set(bar1(2),'DisplayName','RMS');
set(bar1(1),'DisplayName','Diferencia absoluta');

% Create title
title({'Comparación generadores'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.514285743236542 9.48571395874023]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1400]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(gca,'xtick',1:9);
set(gca,'xticklabel', {'twister' 'simdTwister' 'combRecursive' 'multFibonacci' 'philox' 'threefry' 'v4' 'v5normal' 'v5uniform'});
% Create legend
legend(axes1,'show');


